workflows:
  build-android-apk:
    name: ASTI-WALLET Android APK Build
    environment:
      vars:
        NODE_VERSION: 20
      node: $NODE_VERSION
    scripts:
      - |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/opt/homebrew/bin/brew shellenv)"
        brew install watchman
        brew install nvm
        nvm install 20.19.2
        corepack enable
        corepack prepare yarn@4.9.2 --activate
        yarn install
        yarn build
        cd samples/app/android
        ./gradlew assembleRelease
    artifacts:
      - samples/app/android/app/build/outputs/**/*.apk