workflows:
  build-bifold:
    name: ASTI WALLET V3 - Bifold Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    triggering:
      events:
        - push
        - pull_request
    environment:
       vars:
        NODE_VERSION: 20
        node: $NODE_VERSION
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Run Android build
        script: yarn android:build
      - name: Build Android APK
        script: echo "Building Android APK..."
                cd samples/app/android
                ./gradlew assembleRelease
    artifacts:
      - samples/app/android/app/build/outputs/**/*.apk
