workflows:
  build-bifold:
    name: ASTI WALLET V3 - Bifold Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    triggering:
      events:
        - push
        - pull_request
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Run Android build
        script: yarn android:build

